spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: admin
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  graphql:
    graphiql:
      enabled: true

server:
  port: 8080 